name: Python Wheels

env:
  MACOSX_DEPLOYMENT_TARGET: 10.9
  DOCKER_IMAGE: quay.io/pypa/manylinux2014_aarch64

on:
  push:
    tags: [ "*" ]
jobs:
  build:
    runs-on: ["self-hosted", "ARM64"]
    strategy:
      matrix:
        pyver: ['3.9', '3.10', '3.11', '3.12', '3.13']

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git name
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git --version

      - name: Package Python 3.9
        if: matrix.pyver == '3.9'
        run: docker run --rm -v ${{github.workspace}}/:/io $DOCKER_IMAGE sh /io/tools/package_linux.sh /io /io/dist local OFF Release cp39-cp39

      - name: Package Python 3.10
        if: matrix.pyver == '3.10'
        run: docker run --rm -v ${{github.workspace}}/:/io $DOCKER_IMAGE sh /io/tools/package_linux.sh /io /io/dist local OFF Release cp310-cp310

      - name: Package Python 3.11
        if: matrix.pyver == '3.11'
        run: docker run --rm -v ${{github.workspace}}/:/io $DOCKER_IMAGE sh /io/tools/package_linux.sh /io /io/dist local OFF Release cp311-cp311

      - name: Package Python 3.12
        if: matrix.pyver == '3.12'
        run: docker run --rm -v ${{github.workspace}}/:/io $DOCKER_IMAGE sh /io/tools/package_linux.sh /io /io/dist local OFF Release cp312-cp312

      - name: Package Python 3.13
        if: matrix.pyver == '3.13'
        run: docker run --rm -v ${{github.workspace}}/:/io $DOCKER_IMAGE sh /io/tools/package_linux.sh /io /io/dist local OFF Release cp313-cp313

      - uses: actions/upload-artifact@v4
        with:
          name: artifact_${{matrix.pyver}}_aarch64
          path: dist/*.whl
